#!/bin/bash

start () {
    remove 2> /dev/null
    systemctl start keepalived
}
stop () {
    remove
}
remove () {
    systemctl stop keepalived
}

# Avoid changing anything below here.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
